//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credentials_Roles
    {
        public int Id { get; set; }
        public Nullable<int> CredentialsId { get; set; }
        public string RolesId { get; set; }
    
        public virtual Credential Credential { get; set; }
        public virtual Role Role { get; set; }
    }
}
