//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Student
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> OldStudentId { get; set; }
        public Nullable<int> CurriculumId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual Document Document { get; set; }
        public virtual OldRollNumber OldRollNumber { get; set; }
        public virtual Student Student { get; set; }
    }
}
