//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CapstoneProjectEntities : DbContext
    {
        public CapstoneProjectEntities()
            : base("name=CapstoneProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<Credentials_Roles> Credentials_Roles { get; set; }
        public virtual DbSet<Dynamic_Menu> Dynamic_Menu { get; set; }
        public virtual DbSet<MarkComponent> MarkComponents { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<OldRollNumber> OldRollNumbers { get; set; }
        public virtual DbSet<Prequisite> Prequisites { get; set; }
        public virtual DbSet<RealSemester> RealSemesters { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolesAuthority> RolesAuthorities { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Status> Student_Status { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Subject_MarkComponent> Subject_MarkComponent { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
    }
}
