//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldRollNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OldRollNumber()
        {
            this.Document_Student = new HashSet<Document_Student>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string OldRollNumber1 { get; set; }
        public Nullable<System.DateTime> ChangedCurriculumDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_Student> Document_Student { get; set; }
        public virtual Program Program { get; set; }
        public virtual Student Student { get; set; }
    }
}
