//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldRollNumber
    {
        public int Id { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string OldRollNumber1 { get; set; }
        public Nullable<System.DateTime> ChangedCurriculumDate { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
