//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prequisite
    {
        public string SubjectId { get; set; }
        public string PrequisiteSubs { get; set; }
        public Nullable<int> FailMark { get; set; }
        public string EffectionSemester { get; set; }
        public string NewPrequisiteSubs { get; set; }
        public Nullable<int> NewFailMark { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
