//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesAuthority
    {
        public int Id { get; set; }
        public string RolesId { get; set; }
        public int MenuId { get; set; }
    
        public virtual Dynamic_Menu Dynamic_Menu { get; set; }
        public virtual Role Role { get; set; }
    }
}
