//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject_Curriculum
    {
        public int Id { get; set; }
        public string SubjectId { get; set; }
        public Nullable<int> CurriculumId { get; set; }
        public Nullable<int> OrdinalNumber { get; set; }
        public Nullable<int> TermNumber { get; set; }
        public Nullable<int> SubjectCredits { get; set; }
        public Nullable<bool> Required { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
